### PR TITLE
Added method to get custom conversions for ad account

### PR DESCRIPTION
**Pull request by karnstrand**
This functionality was not present in the python sdk previously

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by arsalan31** [comment]
Hi karnstrand, 

Thanks for creating the function, could you please post some sample code for it e.g.

from facebookads.adobjects.ad import Ad

ad = Ad(parent_id='act_<AD_ACCOUNT_ID>')
ad.update({
    Ad.Field.adset_id: <AD_SET_ID>,
    Ad.Field.name: 'Offsite Conversions Ad',
    Ad.Field.creative: {
        'creative_id': <CREATIVE_ID>,
    },
    Ad.Field.tracking_specs: [
        {
            'action.type': 'offsite_conversion',
            'fb_pixel': <PIXEL_ID>,
        },
    ],
})
ad.remote_create(params={
    'status': Ad.Status.paused,
})

Thanks in advance.

**Comment by karnstrand** [comment]
```python
from facebookads.adobjects.adaccount import AdAccount

account = AdAccount('act_<AD_ACCOUNT_ID>')
conversions = account.get_custom_conversions(fields=[
    'id', 
    'name', 
    'custom_event_type', 
    'pixel_rule'
])
```

**Comment by mp3il** [comment]
why wasn't this merged?

**Comment by jatinder85** [comment]
Any update on this?

**Comment by guxufb** [comment]
Sorry @karnstrand, we cannot accept the pull request on auto-generated files.  All the auto-generated files have the following comments at the beginning of files.  We need some time to update the internal data and make the method available for supported all languages. 

"""
This class is auto-generated.
For any issues or feature requests related to this class, please let us know on
github and we'll fix in our codegen framework. We'll not be able to accept
pull request for this class.
"""

**Comment by stajilov** [comment]
So was it merged? don't see this functionality in 2.11 :(

**Pull request closed without merging**
