### PR TITLE
Fix bug with pagination

### PR DESCRIPTION
**Pull request by SlavaSkvortsov**
It should be a dict -_- 
Could you use Mypy or test or, better, both?

### CODE REVIEW

**Comment by nandanrao** [comment]
omg thank you @SlavaSkvortsov...

**Comment by nathand8** [comment]
Can we get this merged and released plz?

**Comment by jen-soft** [comment]
`
class Cursor(object):

    def load_next_page(self):
        """Queries server for more nodes and loads them into the internal queue.
        Returns:
            True if successful, else False.
        """
        if self._finished_iteration:
            return False

        if (
            self._include_summary and
            'default_summary' not in self.params and
            'summary' not in self.params
        ):
            self.params['summary'] = True  # <==============================================(! 1)

        response_obj = self._api.call(
            'GET',
            self._path,
            params=self.params,
        )
        response = response_obj.json()
        self._headers = response_obj.headers()

        if 'paging' in response and 'next' in response['paging']:
            self._path = response['paging']['next']
            self.params = []  # <==============================================(! 2)
        else:
            # Indicate if this was the last page
            self._finished_iteration = True

`

**Comment by jen-soft** [comment]
quick fix outside of library
    def get_ad_accounts(self):
        fb_user = fb.User('me', api=self._api)
        _request = fb_user.get_ad_accounts(
            fields=[
                fb.AdAccount.Field.id,
                fb.AdAccount.Field.account_id,
                fb.AdAccount.Field.name,
                fb.AdAccount.Field.account_status,
                fb.AdAccount.Field.currency,
                fb.AdAccount.Field.timezone_id,
            ],
            pending=True
        )
        #
        response = _request.execute()
        # ------------------------------------------------------------ #
        result = []
        for item in response:
            # fixme: remove after facebook will fix it
            # from facebook_business.api import Cursor
            # - - -
            if isinstance(response.params, list):
                assert len(response.params) == 0
                response.params = {} # <=====================================(*)
            #
            # - - -
            assert isinstance(item, fb.AdAccount)
            attrs = item.export_all_data()

**Comment by SlavaSkvortsov** [comment]
The quick fix is to use 7.0.3 :)

**Comment by aljinovic** [comment]
Pagination is still not fixed, is there a reason why this can't be merged, it's an obvious bug?

**Comment by ppleskov** [comment]
pls merge :)

**Comment by pradeepadi88** [comment]
can you please merge this change?

**Comment by AydarAkhmetzyanov** [comment]
Could you please merge this ASAP, wondering how 8.0 was published with broken pagination.

**Comment by maxexcloo** [comment]
Could this be merged please?

**Comment by nicholricc** [comment]
can this be merged in?  any idea what's causing the delay?

**Comment by brandonkane** [comment]
This should be closed, the fix is already in master:  https://github.com/facebook/facebook-python-business-sdk/commit/422d88aeb8e057b92820b430c1006964c1ae887f

If you look at the file diff on this PR there are no changes left, after SlavaSkvortsov rebased it to master a couple days ago there is nothing left to merge.

**Comment by AydarAkhmetzyanov** [comment]
> This should be closed, the fix is already in master: [422d88a](https://github.com/facebook/facebook-python-business-sdk/commit/422d88aeb8e057b92820b430c1006964c1ae887f)
> 
> If you look at the file diff on this PR there are no changes left, after SlavaSkvortsov rebased it to master a couple days ago there is nothing left to merge.

Good. But it is a critical bug and fix is not yet released as a new version for pip.

**Review by alshamiri5 — APPROVED** [review]

**Comment by jingping2015** [comment]
Since v8.0.2, this bug should be fixed.

**Pull request closed without merging**
