### PR TITLE
update api and sdk version to v13

### PR DESCRIPTION
**Pull request by marcosmarxm**

### CODE REVIEW

**Comment by harshithmullapudi** [comment]
@marcosmarxm can you sign the CLA here?

**Comment by marcosmarxm** [comment]
> @marcosmarxm can you sign the CLA here?

done

**Comment by marcosmarxm** [comment]
@thiagocmoraes would you help me here? There is any workflow I need to follow to get a review?

**Comment by oseh-stake** [comment]
Thank you @marcosmarxm 🙌  - have been encountering this issue as well

**Comment by bxjw** [comment]
would also like this merged. Trying to understand why Facebook's own official SDK wouldn't update along with their API versions

**Comment by collinmpage** [comment]
Has this issue been resolved yet?

**Comment by jurrigerretsen** [comment]
Would also like to see this merged it is blocking me right now

**Comment by oseh-stake** [comment]
> would also like this merged. Trying to understand why Facebook's own official SDK wouldn't update along with their API versions

Beggars belief

**Comment by kfallows-adl** [comment]
Please merge this!!

**Comment by beubeu13220** [comment]
We are also waiting this merge 👍

**Comment by Luttik** [comment]
Hé this merge is very important to us since the facebook API has now started throwing error codes if you use v12:

**Example**
```
Status:  400
  Response:
    {
      "error": {
        "message": "(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v13.0.",
        "type": "OAuthException",
        "code": 2635,
        "fbtrace_id": "AAOEMw96o0wSs67yOb0pYQy"
      }
    }
```

**Comment by hwebservices** [comment]
Screenshot 2022-03-19 at 11 49 28


from facebook_business.api import FacebookAdsApi
from facebook_business.adobjects.adaccount import AdAccount

my_app_id = 'xxxxxx'
my_app_secret = 'xxxxx'
my_access_token = 'xxxxx'
api_version = 'v13.0'
account_id = 'act_9165******81168'

FacebookAdsApi.init(my_app_id, my_app_secret, my_access_token, api_version)
my_account = AdAccount(account_id)


Error:
alueError: Account ID provided in FacebookAdsApi.set_default_account_id expects a string that begins with 'act_'

Can you fix this, please?

**Comment by LorienMan** [comment]
I wonder how the API version was deprecated without an official library release 😬 Please merge!

**Comment by laskoviymishka** [comment]
I wonder how that happened -  https://developers.facebook.com/blog/post/2022/02/08/introducing-facebook-graph-marketing-api-v13/
Per official release - Marketing API v12.0 will deprecate on 08/09/2022, but its deprecated couple weeks ago. I believe someone should merge this ASAP or rollback API deprication

**Comment by osehmathias** [comment]
This is truly unbelievable 

I reached out to Facebook 

The response was,  "This is a community-maintained package and not actively maintained by Facebook. As a result, we can not offer support in this instance. 

I asked, "Who can I contact about merging this PR?"

The response, "We can not off support for community-maintained packages.

**Comment by Just1B** [comment]
Community-maintained package ? it's very confusing because in the contributing file below, they say that it's an internal tools exposed publicly by team members after reviews.

https://github.com/facebook/facebook-python-business-sdk/blob/main/CONTRIBUTING.md

> Our Development Process
The Facebook Ads API SDK for Python is currently developed in Facebook's internal repositories and then exported out to GitHub by a Facebook team member. We invite you to submit pull requests directly to GitHub and, after review, these can be merged into the project.

**Comment by pjatx** [comment]
Please merge!

**Comment by DeTeam** [comment]
Seems like there are no breaking changes expected 12 -> 13 for business SDK (right?).
@jingping2015 @donglinw-fb could you have a look and maybe support with releasing a new version of this SDK? 🙏

**Comment by DeTeam** [comment]
@marcosmarxm https://github.com/facebook/facebook-python-business-sdk/blob/main/facebook_business/apiconfig.py#L22-L23 — seems like it's already 13 (was autogenerated a year ago in https://github.com/facebook/facebook-python-business-sdk/commit/5cfd5cc9cc6730c9bba16a679464d839106010e0 with some involvement from @jawwad). 

https://pypi.org/project/facebook-business/#history — seems like the version wasn't updated in pypi, @jawwad, could you maybe have a look? 😊

**Comment by marcosmarxm** [comment]
The SDK was updated to 13.0.0 version.

**Pull request closed without merging**
