### PR TITLE
Added per-Cursor headers support.

### PR DESCRIPTION
**Pull request by vitos555**
Main intent for this PR is to give visibility into per-request headers. With this change API users can monitor X-FB-Ads-Insights-Throttle and  X-Ad-Account-Usage headers themselves and introduce sleeps in their code if needed.

### CODE REVIEW

**Comment by vitalious** [comment]
Finally found this gem.
Can this please be merged? Last thing I want to do is fork this project so that the returned objects have a response property.

**Comment by dpatz** [comment]
@jingping2015 Would you mind merging this?

**Comment by dpatz** [comment]
@jingping2015 Thanks!

**Comment by jingping2015** [comment]
It should available for next release.

**Pull request closed without merging**
