### PR TITLE
Add AsyncJob.poll() method

### PR DESCRIPTION
**Pull request by m-vdb**
Hi there,

I feel like every one will need this. I implemented a util method in my project to do this, but I think it's more logical as a method of the AsyncJob. Here it is \o/.

Also, I'd like to test it, by I need a mocking library (see my description of https://github.com/facebook/facebook-python-ads-sdk/pull/92 that asks to include the mock python module)

Cheers!

### CODE REVIEW

**Comment by fbach** [comment]
+1

**Comment by aparakian** [comment]
+1

**Comment by m-vdb** [comment]
@rituparnamukherjee any chance you could take a look?

**Comment by m-vdb** [comment]
@rituparnamukherjee any chance you could take a look?

**Pull request closed without merging**
