### PR TITLE
Add include_headers parameter for batch operations

### PR DESCRIPTION
**Pull request by MichaelAquilina**
As documented here:
https://developers.facebook.com/docs/graph-api/making-multiple-requests

Specifying this parameter would provide a noticeable performance improvements in systems which make lots of API calls in batch.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by guxuoss** [comment]
Thanks MichaelAquilina for the pull request.  We are cleaning up internal process to accommodate the new auto-gen pipeline.  We will be slow on following up with these pull requests.  Please be patient.

**Comment by MichaelAquilina** [comment]
@guxuoss any ETA on when this will be given a look?

**Comment by MichaelAquilina** [comment]
@guxuoss polite ping

**Pull request closed without merging**
