### PR TITLE
Update apiconfig to use version 14 of FB API

### PR DESCRIPTION
**Pull request by WillLiuMH**
FB API version 13 has been deprecated

### CODE REVIEW

**Comment by shzyincu** [comment]
When will the updated version v14.0 be available for python? desperately waiting.

**Comment by tomaszdudek7** [comment]
Also waiting for an update.

**Comment by terrazasrj** [comment]
For those waiting, just update the library's apiconfig.py file and change the value to 14 for both the SDK and JDK.
image

**Comment by shzyincu** [comment]
How long does this generally take to process requests/commits? :(

Still waiting team...

**Comment by riceyrice** [comment]
Building on @terrazasrj suggestion I did this in `__init__py` of my module which is executed before any existing imports from `facebook_business`
```
from facebook_business import apiconfig
apiconfig.ads_api_config['API_VERSION'] = 'v14.0'
for mod in list(sys.modules):
    if mod.startswith('facebook_business') and mod != 'facebook_business.apiconfig':
        del sys.modules[mod]
```
Obviously having a real v14 client would be much better!

**Comment by antocapp** [comment]
annoying, please update

**Comment by biancaclazzaris** [comment]
Hi, I also need this change, it's urgent!!

**Comment by ajendrex** [comment]
I executed the [CodeGenerator](https://github.com/facebook/facebook-business-sdk-codegen) against v14 and got the following changes:

```
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    examples/AdAccountActivityNode.py
	deleted:    examples/AdAccountAdCreativesEdge.py
	deleted:    examples/AdAccountAdCreativesPost.py
	deleted:    examples/AdAccountAdCreativesPost2CreateAdCreativeLinkAd.py
	deleted:    examples/AdAccountAdCreativesPost2CreateLinkAdCallToActionAppInstall.py
	deleted:    examples/AdAccountAdCreativesPost2CreateLinkAdImageCrop.py
	deleted:    examples/AdAccountAdCreativesPost2CreateMAIDPA.py
	deleted:    examples/AdAccountAdCreativesPost2CreateVideoLeadAd.py
	deleted:    examples/AdAccountAdCreativesPost2CreateVideoPageLikeAd.py
	deleted:    examples/AdAccountAdCreativesPost3CreateAdCreativePageLike.py
	deleted:    examples/AdAccountAdCreativesPost3CreateAssetFeedSpec.py
	deleted:    examples/AdAccountAdCreativesPost3CreateCarouselCallToActionAppInstall.py
	deleted:    examples/AdAccountAdCreativesPost3CreateDynamicAdCustomization.py
	deleted:    examples/AdAccountAdCreativesPostCreateAdCreative.py
	deleted:    examples/AdAccountAdCreativesPostCreateAdCreativeCanvas.py
	deleted:    examples/AdAccountAdCreativesPostCreateAdCreativeCustomizationCanvasDV.py
	deleted:    examples/AdAccountAdCreativesPostCreateAdCreativeCustomizationCanvasImage.py
	deleted:    examples/AdAccountAdCreativesPostCreateAdCreativeCustomizationCanvasVideo.py
	deleted:    examples/AdAccountAdSetsPost2CreateMAIA.py
	deleted:    examples/AdAccountAdSetsPostAdSetCreateCpa.py
	deleted:    examples/AdAccountAdSetsPostAdSetCreateCpaAppEvents.py
	deleted:    examples/AdAccountAdSetsPostBehaviorTargeting.py
	deleted:    examples/AdAccountAdSetsPostBidMultiplier.py
	deleted:    examples/AdAccountAdSetsPostCreateAdSet.py
	deleted:    examples/AdAccountAdSetsPostCreateAudienceNetwork.py
	deleted:    examples/AdAccountAdSetsPostDailyBudget20.py
	deleted:    examples/AdAccountAdSetsPostDemographicTargeting.py
	deleted:    examples/AdAccountAdSetsPostInterestTargeting.py
	deleted:    examples/AdAccountAdSetsPostLifetimeBudget200Duration10Days.py
	deleted:    examples/AdAccountAdSetsPostOfferClaim.py
	deleted:    examples/AdAccountAdSetsPostOptimizePostEngagement.py
	deleted:    examples/AdAccountAdSetsPostPageLikes.py
	deleted:    examples/AdAccountAdSetsPostPlacementTargeting.py
	deleted:    examples/AdAccountAdSetsPostReach.py
	deleted:    examples/AdAccountAdVideosPost.py
	deleted:    examples/AdAccountAdsPixelEdgeGetPixelCode.py
	deleted:    examples/AdAccountAdsPixelsPost.py
	deleted:    examples/AdAccountAdsPost.py
	deleted:    examples/AdAccountAdsPostAdsRedownload.py
	deleted:    examples/AdAccountAdsPostOfferClaim.py
	deleted:    examples/AdAccountAdsPostTrackingPostEngagement.py
	deleted:    examples/AdAccountCampaignsEdge.py
	deleted:    examples/AdAccountCampaignsPostConversions.py
	deleted:    examples/AdAccountCampaignsPostEventResponses.py
	deleted:    examples/AdAccountCampaignsPostLeadGen.py
	deleted:    examples/AdAccountCampaignsPostLinkClicks.py
	deleted:    examples/AdAccountCampaignsPostLocalAwareness.py
	deleted:    examples/AdAccountCampaignsPostMAIA.py
	deleted:    examples/AdAccountCampaignsPostMAIDPA.py
	deleted:    examples/AdAccountCampaignsPostOfferClaims.py
	deleted:    examples/AdAccountCampaignsPostPageLikes.py
	deleted:    examples/AdAccountCampaignsPostPostEngagement.py
	deleted:    examples/AdAccountCampaignsPostStoreCampaign.py
	deleted:    examples/AdAccountCampaignsPostVideoViews.py
	deleted:    examples/AdAccountCustomAudiencesEdge.py
	deleted:    examples/AdAccountCustomAudiencesEdgeDataSourceSubtype.py
	deleted:    examples/AdAccountCustomAudiencesPostCreateCustomAudience.py
	deleted:    examples/AdAccountCustomAudiencesPostDynamicEventValueBasedLookalikeCustomAudience.py
	deleted:    examples/AdAccountCustomAudiencesPostDynamicValueBasedLookalikeCustomAudience.py
	deleted:    examples/AdAccountCustomAudiencesPostPlatformCustomAudienceMACARule.py
	deleted:    examples/AdAccountCustomAudiencesPostPlatformECAExclusions.py
	deleted:    examples/AdAccountCustomAudiencesPostPlatformECAMultiFilters.py
	deleted:    examples/AdAccountCustomAudiencesPostPlatformECAMultiPages.py
	deleted:    examples/AdAccountCustomAudiencesPostPlatformEngagementCustomAudience.py
	deleted:    examples/AdAccountCustomAudiencesPostPlatformWebsiteCustomAudience.py
	deleted:    examples/AdAccountCustomAudiencesPostValueBasedCustomAudience.py
	deleted:    examples/AdAccountCustomAudiencesPostValueBasedLookalikeCustomAudience.py
	deleted:    examples/AdAccountGeneratePreviewsEdge.py
	deleted:    examples/AdAccountGeneratePreviewsEdgeDesktopWithStoryId.py
	deleted:    examples/AdAccountGeneratePreviewsEdgeInstagramStandards.py
	deleted:    examples/AdAccountGeneratePreviewsEdgeMaiaWithObjectStorySpec.py
	deleted:    examples/AdAccountNode.py
	deleted:    examples/AdAccountProductAudiencesPostIphoneViewNoPurchase.py
	deleted:    examples/AdAccountProductAudiencesPostNoPurchase.py
	deleted:    examples/AdAccountReachEstimate.py
	deleted:    examples/AdCampaignActivityNode.py
	deleted:    examples/AdCampaignGroupActivityNode.py
	deleted:    examples/AdCampaignGroupAdsEdge.py
	deleted:    examples/AdCampaignGroupAdsEdgeAdgroupsWithStatusArchived.py
	deleted:    examples/AdCampaignGroupAdsetsEdge.py
	deleted:    examples/AdCampaignNode.py
	deleted:    examples/AdCampaignPost.py
	deleted:    examples/AdCampaignPostAdsetUpdateCpa.py
	deleted:    examples/AdCreativeCreativeInsightsEdge.py
	deleted:    examples/AdCreativeNode.py
	deleted:    examples/AdCreativeNodeRead.py
	deleted:    examples/AdCreativeNodeReadInstagramPermalinkUrl.py
	deleted:    examples/AdCreativePreviewsEdge.py
	deleted:    examples/AdCreativePreviewsEdgePreview.py
	deleted:    examples/AdCreativePreviewsEdgePreviewDynamicAds.py
	deleted:    examples/AdCreativePreviewsEdgePreviewDynamicAdsWithCustomizations.py
	deleted:    examples/AdgroupActivityNode.py
	deleted:    examples/AdgroupLeadsEdgeAdgroupLeads.py
	deleted:    examples/AdgroupLeadsEdgeAdgroupLeadsDPA.py
	deleted:    examples/AdgroupLeadsEdgeAdgroupLeadsFiltered.py
	deleted:    examples/AdgroupPost.py
	deleted:    examples/AdgroupPostUpdateStatus.py
	deleted:    examples/AdsInsightsEdgeAdCampaignInsights.py
	deleted:    examples/AdsInsightsEdgeStoreVisitsAdCampaignInsights.py
	deleted:    examples/AdsPixelEventsPost.py
	deleted:    examples/AdsPixelEventsPostCustom.py
	deleted:    examples/AdsPixelSharedAccountsEdge.py
	deleted:    examples/AdsPixelSharedAccountsPost.py
	deleted:    examples/AdsPixelSharedAgenciesEdge.py
	deleted:    examples/BusinessOwnedProductCatalogsPostDestinationCatalog.py
	deleted:    examples/BusinessOwnedProductCatalogsPostFlightCatalog.py
	deleted:    examples/BusinessOwnedProductCatalogsPostHotelCatalog.py
	deleted:    examples/BusinessOwnedProductCatalogsPostProductCatalog.py
	deleted:    examples/CustomAudienceDelete.py
	deleted:    examples/CustomAudienceNode.py
	deleted:    examples/CustomAudienceNodeReadRule.py
	deleted:    examples/CustomAudiencePost.py
	deleted:    examples/CustomAudienceUsersPost.py
	deleted:    examples/CustomAudienceUsersPostCrossPlatform.py
	deleted:    examples/MultiPageFeedCreateThenDelete.py
	deleted:    examples/MultiPromoteYourPage.py
	deleted:    examples/OfflineConversionsCreateOfflineSet.py
	deleted:    examples/PageFeedEdge.py
	deleted:    examples/PageFeedPost.py
	deleted:    examples/PageFeedPostFeedImageDeepLink.py
	deleted:    examples/PageNode.py
	deleted:    examples/PageNodePageSearch.py
	deleted:    examples/PagePhotosEdge.py
	deleted:    examples/PagePhotosPost.py
	deleted:    examples/PagePictureEdge.py
	deleted:    examples/PagePostCommentsEdge.py
	deleted:    examples/PagePostCommentsPost.py
	deleted:    examples/PagePostDelete.py
	deleted:    examples/PagePostNode.py
	deleted:    examples/PagePostPost.py
	deleted:    examples/PagePostsEdge.py
	deleted:    examples/PagePostsEdgePagePostCreateCarousel.py
	deleted:    examples/PageRolesEdge.py
	deleted:    examples/PageSubscribedAppsPost.py
	deleted:    examples/ProductCatalogEventStatsEdge.py
	deleted:    examples/ProductCatalogHotelsPost.py
	deleted:    examples/ProductCatalogHotelsPostUpdateHotelsCatalogSettings.py
	deleted:    examples/ProductCatalogProductFeedsPostProductFeed.py
	deleted:    examples/ProductCatalogProductSetsPostHotelSet.py
	deleted:    examples/ProductCatalogProductSetsPostProductSet.py
	deleted:    examples/UserAccountsEdge.py
	deleted:    examples/UserAdAccountsEdge.py
	deleted:    examples/UserLeadGenInfoNode.py
	deleted:    examples/UserNode.py
	deleted:    examples/VideoThumbnailsEdge.py
	modified:   facebook_business/__init__.py
	modified:   facebook_business/apiconfig.py
	deleted:    facebook_business/docs_runner/__init__.py
	deleted:    facebook_business/docs_runner/doc_runner.py
	deleted:    facebook_business/docs_runner/get_version.py
	modified:   setup.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	compiled.json

no changes added to commit (use "git add" and/or "git commit -a")
```

lots of files deleted and three of them modified. The three modifications are simply replacing `13.0.0` for `14.0.0`. It doesn't seem that these changes are correct. I'm willing to dedicate more time working on this, but would need some guidance from facebook team to get things right...

**Comment by ayyoubmaulana** [comment]
i need this module, please update :bow:

**Comment by TacoTuesdayX365** [comment]
@jingping2015 or @dmi3coder can you possibly help out with getting this pushed through? the SDK is been broken for over a month.

**Comment by rabidaudio** [comment]
FYI it does seem they published [14.0.0](https://github.com/facebook/facebook-python-business-sdk/tree/14.0.0) on June 30th, they just didn't update this PR or the changelog.

**Pull request closed without merging**
