### PR TITLE
Fix is_success() check for non-json response which body contains 'success' somehow.

### PR DESCRIPTION
**Pull request by madbird1304**
I was receiving payload like below frequently with 502 responses. It leads to inconsistent response handling in further SDK code and finally ends up with `TypeError: string indices must be integers` sooner or later.
20201026_17h32m19s_grim
20201026_17h33m10s_grim

### CODE REVIEW

**Comment by jingping2015** [comment]
Hi, thanks for submit this PR, can you sign our Contributor License Agreement.

**Comment by madbird1304** [comment]
Hi, @jingping2015 , may I ask you to restart the CI pipeline?

**Comment by madbird1304** [comment]
Is there anybody in there?

**Comment by madbird1304** [comment]
Tired of seeing it in `open PRs`

**Pull request closed without merging**
