### PR TITLE
Fix AsyncJob.__nonzero__: KeyError

### PR DESCRIPTION
**Pull request by m-vdb**
Hi there,

This PR includes a fix of `AsyncJob.__nonzero__` that could raise a `KeyError` if the `AsyncJob` was never read. I think it's not what we / I / users want.

Finally, I'd like to test extensively the `get_result()` method, and I'd like to use [this module](https://pypi.python.org/pypi/mock). It's kind of the best module to have mocks in your tests. I've used it for years ^^. Would you consider using it and if yes, where should I include it?

Cheers!

### CODE REVIEW

**Comment by m-vdb** [comment]
I might have made a mistake for the `get_result()` part I don't know why I thought there was a bug. But the `__nonzero__` stuff is still relevant. Let me know if you want me to do another PR.

Btw, tests are failing because in python3, `__nonzero__` -> `__bool__`

**Comment by fbach** [comment]
+1

**Comment by aparakian** [comment]
+1

**Comment by m-vdb** [comment]
@rituparnamukherjee any chance you could take a look?

**Comment by m-vdb** [comment]
@rituparnamukherjee any chance you could take a look?

**Pull request closed without merging**
