### PR TITLE
    python3.7 "async" keyword fixes & Travis CI config improvements 

### PR DESCRIPTION
**Pull request by alternativshik**
Keyword arg async was renamed to is_async for python 3.7 support

### CODE REVIEW

**Comment by avborhanian** [comment]
Looks like they just updated their generated code to use is_async instead!

**Comment by alternativshik** [comment]
@avborhanian Don't see any async changes in latest Auto generated code(17 hours ago)...

**Comment by avborhanian** [comment]
https://github.com/facebook/facebook-python-business-sdk/blob/ccef9154d2c201ef71ea5ac94326b9f10b122e56/facebook_business/adobjects/page.py#L1263

Looks like it was done in the one last time, just not pushed to PyPi.

**Comment by alternativshik** [comment]
@avborhanian LOL, they fix it only in ONE place? 
There are many files with async keyword still with "async"

https://github.com/facebook/facebook-python-business-sdk/blob/master/facebook_business/adobjects/abstractcrudobject.py#L552

**Comment by avborhanian** [comment]
LMAO you're right, it's only a few. I got hit by this because I updated the lib this morning, apparently only 8 places. Still some progress to make.

**Comment by leahein** [comment]
Bumping this -- this is still an issue in version `3.1.2`, specifically in:
* facebook_business/adobjects/helpers/businessmixin.py
* facebook_business/adobjects/abstractcrudobject.py

**Comment by revmischa** [comment]
This issue is preventing use of the latest stable python release 3.7.0. Please put this on pypi.

**Comment by alternativshik** [comment]
@revmischa Just install it from github and use.

**Comment by revmischa** [comment]
@alternativshik I installed it from your github and then all of my requests strangely started using v3.0 instead of v3.1. Any idea why?

        "message": "(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v3.1.",

I don't get it when using the PyPI version

**Comment by alternativshik** [comment]
Install It from facebook master brunch not from my github...

**Comment by revmischa** [comment]
It's not merged to FB master branch is it? https://github.com/facebook/facebook-python-business-sdk/commits/master

**Comment by arorasudhir** [comment]
Any update on this? I am still facing the issue in https://github.com/facebook/facebook-python-business-sdk/blob/master/facebook_business/adobjects/abstractcrudobject.py#L552

**Comment by revmischa** [comment]
This is preventing upgrading to 3.7

**Comment by hecvd** [comment]
Any update on this?

**Comment by codytwinton** [comment]
This has been resolved in `master`

**Pull request closed without merging**
